packaging_format = 2

id = "cloudlog"
name = "CloudLog"
description.en = "Web based amateur radio logging application"
description.fr = "Application Web d'enregistrement radioamateur"

version = "2.4.6~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://www.cloudlog.co.uk"
code = "https://github.com/magicbug/Cloudlog"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/magicbug/Cloudlog/archive/refs/tags/2.4.6.tar.gz"
        sha256 = "aba71715f510233f87403be57703ed4952375f2c674d691b26d3aa1341774ba9"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.0-curl, php8.0-mbstring, php8.0-mysql, php8.0-xml"

    [resources.database]
    type = "mysql"
