packaging_format = 2

id = "cloudlog"
name = "CloudLog"
description.en = "Web based amateur radio logging application"
description.fr = "Application Web d'enregistrement radioamateur"

version = "2.6.15~ynh1"

maintainers = [ ]

[upstream]
license = "MIT"
website = "https://www.cloudlog.co.uk"
code = "https://github.com/magicbug/Cloudlog"

[integration]
yunohost = ">= 11.2.29"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/magicbug/Cloudlog/archive/refs/tags/2.6.15.tar.gz"
        sha256 = "bfe098e978f03d53d244565e71a8c959a718034525bdb7496ffa4f1a834fee37"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.2-curl, php8.2-mbstring, php8.2-mysql, php8.2-xml"

    [resources.database]
    type = "mysql"
