packaging_format = 2

id = "cloudlog"
name = "CloudLog"
description.en = "Web based amateur radio logging application"
description.fr = "Application Web d'enregistrement radioamateur"

version = "2.6.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://www.cloudlog.co.uk"
code = "https://github.com/magicbug/Cloudlog"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/magicbug/Cloudlog/archive/refs/tags/2.6.0.tar.gz"
        sha256 = "8f0cd38d7738227d6ae8acda07e944dd215416ef3f7866cc418d7a1f864eaad8"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.2-curl, php8.2-mbstring, php8.2-mysql, php8.2-xml"

    [resources.database]
    type = "mysql"
